Mostly English adjustments
dokato/healthcareonlinesources pull request #19
Opened 2020-03-10 14:25 UTC by NiCl2

2020-03-10 15:29 UTC, dokato requested changes
Minor comment needs to be fixed.

2020-03-10 15:29 UTC, dokato commented on Shiny/server.R
> +        #     "' that is bad.", "</b></font>")
We should remove that entirely if we decided to skip that part.

2020-06-15 10:01 UTC, NiCl2 commented
OK I think I've made those changes (removed unnecessary comments) so you could merge these changes

2020-06-15 11:33 UTC, dokato approved these changes

2020-06-15 11:34 UTC, merged